name: Deploy Docs

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy the docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./docs/yarn.lock 

      - name: Install dependencies
        run: cd docs && yarn install --frozen-lockfile
      
      - name: Build website
        run: cd docs && yarn build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
          publish_dir: ./docs/build
          cname: docs.trustacks.io
